[tool.poetry]
name = "auth"
version = "0.1.0"
description = "auth micro service"
authors = ["嘉然今天吃什么 <jsclndnz@outlook.com>"]
license = "Apache"

[tool.poetry.dependencies]
python = "^3.9"
sanic = "^21.12.1"
tortoise-orm = "^0.18.1"
aiomysql = "^0.0.22"
aiosqlite = "^0.17.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
